version: "3"
services:
  smart-pg:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: smart
      POSTGRES_PASSWORD: admin
  smart-mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: smart
  nest-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nest-app
    ports:
      - 3333:3333
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: smart
      DB_HOST: smart-pg
      DB_PORT: 5432
      MONGO_URI: mongodb://smart-mongo/smart
    depends_on:
      - smart-pg
      - smart-mongo