apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: cG9zdGdyZXM=
  password: YWRtaW4=